repos:
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.0
    hooks:
    -   id: terraform_fmt
    -   id: terraform_validate
    -   id: terraform_docs
    -   id: terraform_tflint
        args:
        - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl

-   repo: https://github.com/bridgecrewio/checkov.git
    rev: 2.3.364
    hooks:
    -   id: checkov
        args: [
            "--quiet",
            "--directory", ".",
            "--skip-path", ".terraform",
            "--framework", "terraform"
        ]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=500']