name: Terraform Security Scan

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  terraform-security:
    name: Terraform Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check -recursive
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init -backend=false

    - name: Terraform Validate
      id: validate
      run: terraform validate

    - name: TFLint
      uses: reviewdog/action-tflint@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
        tflint_rulesets: terraform aws google
        
    - name: Run Checkov
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: .
        framework: terraform
        skip_check: CKV_AWS_144,CKV_AWS_145
        quiet: true
        soft_fail: true
        output_format: sarif
        output_file: checkov-results.sarif
      
    - name: Upload Checkov SARIF report
      uses: github/codeql-action/upload-sarif@v2
      if: success() || failure()
      with:
        sarif_file: checkov-results.sarif
        category: checkov

    - name: Run KICS scan
      uses: checkmarx/kics-github-action@v1.7.0
      with:
        path: .
        output_path: kics-results
        platform_type: terraform
        output_formats: sarif
        exclude_paths: ".terraform,**/.terraform"
        fail_on: high
        
    - name: Upload KICS SARIF report
      uses: github/codeql-action/upload-sarif@v2
      if: success() || failure()
      with:
        sarif_file: kics-results/results.sarif
        category: kics